// stubs/react-tw/resources/js/react/components/DangerButton.tsx
export default function DangerButton({ className = "", children, ...props }: { [key: string]: any }) {
    return (
        <button {...props} className={`inline-flex items-center px-4 py-2 bg-red-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-500 active:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition ease-in-out duration-150 ${className}`}>
            {children}
        </button>
    )
}

// stubs/vue-tw/resources/js/vue/components/DangerButton.vue
<template>
    <button type="submit"
        class="inline-flex items-center px-4 py-2 bg-red-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-500 active:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition ease-in-out duration-150">
        <slot />
    </button>
</template>

<script setup lang="ts">

</script>

<style scoped></style>
