// stubs/react-tw/resources/js/react/components/InputError.tsx
interface InputErrorProp {
    className?: string,
    messages: string[]
}

export default function InputError({ className = "", messages }: InputErrorProp) {
    return (
        <ul className={`text-sm text-red-600 space-y-1 ${className}`}>
            {messages.map((message,index) => {
                return <li key={index}>{message}</li>
            })}
        </ul>
    )
}

// stubs/vue-tw/resources/js/vue/components/InputError.vue
<template>
    <ul class="text-sm text-red-600 space-y-1">
        <li v-for="message in messages">{{ message }}</li>
    </ul>
</template>

<script setup lang="ts">
import { defineProps } from "vue";

defineProps({
    messages: {
        required: true,
        type: Array,
    }
})
</script>

<style scoped></style>
