// stubs/react-tw/resources/js/react/components/PrimaryButton.tsx
export default function PrimaryButton({ className = "", children, ...props }: { [key: string]: any }) {
    return (
        <button {...props} className={`inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 focus:bg-gray-700 active:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition ease-in-out duration-150 ${className}`}>
            {children}
        </button>
    )
}

// stubs/vue-tw/resources/js/vue/components/PrimaryButton.vue
<template>
    <button
        class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 focus:bg-gray-700 active:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition ease-in-out duration-150"
        type="submit">
        <slot />
    </button>
</template>

<script setup lang="ts">

</script>

<style lang="scss" scoped></style>
