// stubs/react-bs/resources/js/react/pages/auth/Register.tsx
import App from "@/layouts/App";
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { setFormError } from "@/helpers";
import guestAxios from "@/helpers/axiosGuest";

export default function Register() {
  const navigate = useNavigate();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [password_confirmation, setPasswordConfirmation] = useState("");
  const [error, setError] = useState<{ [key: string]: string[] }>({});
  const submitForm = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const response = await guestAxios.post("register", {
      name,
      email,
      password,
      password_confirmation,
    });

    switch (response.status) {
      case 200:
        guestAxios
          .post("login", {
            email,
            password,
          })
          .then((response) => {
            switch (response.status) {
              case 200:
                return navigate("/home");
              default:
                return navigate("/login");
            }
          });
        break;
      case 422:
        setError(setFormError(response));
        return false;
      case 401:
        const { message } = response.data;

        setError({
          email: [message],
        });

        return false;
      default:
        return false;
    }
  };

  return (
    <App>
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-md-8">
            <div className="card">
              <div className="card-header">Register</div>
              <div className="card-body">
                <form onSubmit={submitForm}>
                  <div className="row mb-3">
                    <label
                      htmlFor="name"
                      className="col-md-4 col-form-label text-md-end"
                    >
                      Name
                    </label>
                    <div className="col-md-6">
                      <input
                        id="name"
                        type="text"
                        className={`form-control ${error.name && "is-invalid"}`}
                        value={name}
                        onChange={(e: React.ChangeEvent<HTMLInputElement>) => setName(e.target.value)}
                        autoComplete="name"
                      />
                      <span className="invalid-feedback" role="alert">
                        <strong>{error.name}</strong>
                      </span>
                    </div>
                  </div>
                  <div className="row mb-3">
                    <label
                      htmlFor="email"
                      className="col-md-4 col-form-label text-md-end"
                    >
                      Email Address
                    </label>
                    <div className="col-md-6">
                      <input
                        id="email"
                        type="email"
                        className={`form-control ${error.email && "is-invalid"}`}
                        value={email}
                        onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEmail(e.target.value)}
                        autoComplete="email"
                      />
                      <span className="invalid-feedback" role="alert">
                        <strong>{error.email}</strong>
                      </span>
                    </div>
                  </div>
                  <div className="row mb-3">
                    <label
                      htmlFor="password"
                      className="col-md-4 col-form-label text-md-end"
                    >
                      Password
                    </label>
                    <div className="col-md-6">
                      <input
                        id="password"
                        type="password"
                        className={`form-control ${error.password && "is-invalid"}`}
                        value={password}
                        onChange={(e: React.ChangeEvent<HTMLInputElement>) => setPassword(e.target.value)}
                        autoComplete="new-password"
                      />
                      <span className="invalid-feedback" role="alert">
                        <strong>{error.password}</strong>
                      </span>
                    </div>
                  </div>
                  <div className="row mb-3">
                    <label
                      htmlFor="password-confirm"
                      className="col-md-4 col-form-label text-md-end"
                    >
                      Confirm Password
                    </label>
                    <div className="col-md-6">
                      <input
                        id="password-confirm"
                        type="password"
                        className="form-control"
                        value={password_confirmation}
                        onChange={(e: React.ChangeEvent<HTMLInputElement>) => setPasswordConfirmation(e.target.value)}
                        autoComplete="new-password"
                      />
                    </div>
                  </div>
                  <div className="row mb-0">
                    <div className="col-md-6 offset-md-4">
                      <button type="submit" className="btn btn-primary">
                        Register
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </App>
  );
}

// stubs/vue-bs/resources/js/vue/Pages/Auth/Register.vue
<template>
    <App>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Register</div>

                        <div class="card-body">
                            <form @submit.prevent="submitForm">
                                <div class="row mb-3">
                                    <label for="name" class="col-md-4 col-form-label text-md-end">Name</label>

                                    <div class="col-md-6">
                                        <input id="name" type="text"
                                            :class="`form-control ${error.name != null ? 'is-invalid' : ''}`" v-model="name"
                                            autocomplete="name" autofocus>

                                        <span class="invalid-feedback" role="alert" v-if="error.name != null">
                                            <strong>{{ error.name }}</strong>
                                        </span>
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="email" class="col-md-4 col-form-label text-md-end">Email Address</label>

                                    <div class="col-md-6">
                                        <input id="email" type="email"
                                            :class="`form-control ${error.email != null ? 'is-invalid' : ''}`"
                                            v-model="email" autocomplete="email">

                                        <span class="invalid-feedback" role="alert" v-if="error.email != null">
                                            <strong>{{ error.email }}</strong>
                                        </span>
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="password" class="col-md-4 col-form-label text-md-end">Password</label>

                                    <div class="col-md-6">
                                        <input id="password" type="password"
                                            :class="`form-control ${error.password != null ? 'is-invalid' : ''}`"
                                            v-model="password" autocomplete="new-password">

                                        <span class="invalid-feedback" role="alert" v-if="error.password != null">
                                            <strong>{{ error.password }}</strong>
                                        </span>
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="password-confirm" class="col-md-4 col-form-label text-md-end">
                                        Confirm Password
                                    </label>

                                    <div class="col-md-6">
                                        <input id="password-confirm" type="password" class="form-control"
                                            autocomplete="new-password" v-model="password_confirmation">
                                    </div>
                                </div>

                                <div class="row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            Register
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </App>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import { ref } from 'vue';
import type { Ref } from 'vue';
import { useAuthStore } from '@/stores/auth';
import App from '@/components/App.vue';

const router = useRouter();
const authStore = useAuthStore();
const name = ref("");
const email = ref("");
const password = ref("");
const password_confirmation = ref("");
let error: Ref<{ [key: string]: string }> = ref({});


const submitForm = async () => {
    if (await authStore.register({
        name,
        email,
        password,
        password_confirmation,
        error,
    })){
        if(await authStore.login({email,password,error})){
            router.replace({name:"home"})
        }
    }

}
</script>
