// stubs/react-tw/resources/js/react/pages/home/Home.tsx
import App from "@/layouts/App"

export default function Home() {
    return (
        <App header="Dashboard">
            <div className="py-12">
                <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                    <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                        <div className="p-6 text-gray-900">
                            You're logged in!
                        </div>
                    </div>
                </div>
            </div>
        </App>
    )
}

// stubs/vue-tw/resources/js/vue/Pages/Home.vue
<template>
    <App header="Dashboard">
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6 text-gray-900">
                        You're logged in!
                    </div>
                </div>
            </div>
        </div>
    </App>
</template>

<script setup lang="ts">
import App from "@/layouts/App.vue"
</script>

<style scoped></style>
