// stubs/vue-tw/resources/js/vue/components/NavLink.vue
<template>
    <a
        :class="active ? 'inline-flex items-center px-1 pt-1 border-b-2 border-indigo-400 text-sm font-medium leading-5 text-gray-900 focus:outline-none focus:border-indigo-700 transition duration-150 ease-in-out' : 'inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium leading-5 text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out'">
        <slot />
    </a>
</template>

<script setup lang="ts">
import { defineProps } from 'vue';

defineProps({
    active: {
        required: false,
        type: Boolean,
        default: false
    }
})
</script>

<style scoped></style>

// stubs/react-tw/resources/js/react/components/NavLink.tsx
export default function NavLink({ active = false, children, ...props }:{[key:string]:any}) {
    if (active) {
        props.className = "inline-flex items-center px-1 pt-1 border-b-2 border-indigo-400 text-sm font-medium leading-5 text-gray-900 focus:outline-none focus:border-indigo-700 transition duration-150 ease-in-out"
    } else {
        props.className = "inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium leading-5 text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out";
    }

    return (
        <a href="" {...props}>
            {children}
        </a>
    )
}
