// stubs/vue-tw/resources/js/vue/components/ResponsiveNavLink.vue
<template>
    
<a :class="active ? 'block w-full pl-3 pr-4 py-2 border-l-4 border-indigo-400 text-left text-base font-medium text-indigo-700 bg-indigo-50 focus:outline-none focus:text-indigo-800 focus:bg-indigo-100 focus:border-indigo-700 transition duration-150 ease-in-out':'block w-full pl-3 pr-4 py-2 border-l-4 border-transparent text-left text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out'">
 <slot/>
</a>
</template>

<script setup lang="ts">
import { defineProps } from 'vue';

defineProps({
    active:{
        required:false,
        type:Boolean,
        default:false
    }
})
</script>

<style scoped>

</style>

// stubs/react-tw/resources/js/react/components/ResponsiveNavLink.tsx
export default function ResponsiveNavLink({ active = false, children, ...props }: { [key: string]: any }) {
    if (active) {
        props.className = "block w-full pl-3 pr-4 py-2 border-l-4 border-indigo-400 text-left text-base font-medium text-indigo-700 bg-indigo-50 focus:outline-none focus:text-indigo-800 focus:bg-indigo-100 focus:border-indigo-700 transition duration-150 ease-in-out"
    } else {
        props.className = "block w-full pl-3 pr-4 py-2 border-l-4 border-transparent text-left text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out"
    }

    return (
        <a {...props}>
            {children}
        </a>
    )
}
