// stubs/react-bs/resources/js/react/pages/home/Home.tsx
import App from "@/layouts/App";

export default function Home() {
  return (
    <App>
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-md-8">
            <div className="card">
              <div className="card-header">Dashboard</div>
              <div className="card-body">You are logged in!</div>
            </div>
          </div>
        </div>
      </div>
    </App>
  );
}

// stubs/vue-bs/resources/js/vue/Pages/Home.vue
<template>
    <App>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Dashboard</div>

                        <div class="card-body">
                            <!-- @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                                @endif -->

                            You are logged in!
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </App>
</template>

<script setup lang="ts">
import App from "@/components/App.vue"
</script>

<style scoped></style>
