// stubs/vue-tw/resources/js/vue/layouts/Guest.vue
<template>
    <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
        <div>
            <RouterLink :to="{name:'base'}">
                <ApplicationLogo class="w-20 h-20 fill-current text-gray-500"/>
            </RouterLink>
        </div>

        <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
            <slot />
        </div>
    </div>
</template>

<script setup lang="ts">
import {RouterLink} from "vue-router"
import ApplicationLogo from '@/components/ApplicationLogo.vue';
const body = document.body;
body.className = "font-sans text-gray-900 antialiased"
</script>

<style scoped></style>

// stubs/react-tw/resources/js/react/layouts/Guest.tsx
import ApplicationLogo from '@/components/ApplicationLogo';

export default function Guest({children }:{[key:string]:any}) {
  return (
    <div className="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
            <div>
                <a href="/">
                    <ApplicationLogo className="w-20 h-20 fill-current text-gray-500" />
                </a>
            </div>

            <div className="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
                {children }
            </div>
        </div>
  )
}
